name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  BUNDLE_PATH: vendor/bundle
  PARALLEL_TEST_PROCESSORS: 4
  CC_TEST_REPORTER_ID: 8d5fcf7abea6d56c625104a9d1a81140a588a7f546f4fa9de9bc6ffc8feaaf70

jobs:
  setup_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Download Code Climate test-reporter
        run: |
          mkdir -p tmp
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.6.3-linux-amd64 > tmp/test-reporter
          chmod +x tmp/test-reporter

      - name: Upload test-reporter artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-reporter
          path: tmp/test-reporter

  # Create test apps for each Rails version
  testapp:
    runs-on: ubuntu-latest
    needs: setup_coverage
    strategy:
      fail-fast: false
      matrix:
        rails: ['42', '50', '51', '52']
        include:
          - rails: '42'
            gemfile: gemfiles/rails_42.gemfile
          - rails: '50'
            gemfile: gemfiles/rails_50.gemfile
          - rails: '51'
            gemfile: gemfiles/rails_51.gemfile
          - rails: '52'
            gemfile: Gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.5.2'

      - name: Install bundler
        run: gem install bundler -v 1.17.1

      - name: Install dependencies
        run: bundle install --path vendor/bundle --retry 3 --jobs 3

      - name: Create test app
        run: PARALLEL_TEST_PROCESSORS=4 bundle exec rake setup

      - name: Upload test app artifact
        uses: actions/upload-artifact@v4
        with:
          name: testapp-rails${{ matrix.rails }}
          path: spec/rails/rails-*

      - name: Build
        run: bundle exec rake build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-rails${{ matrix.rails }}
          path: pkg/activeadmin-*.gem

  # Test jobs for MRI Ruby versions
  test_mri:
    runs-on: ubuntu-latest
    needs: 
        - setup_coverage
        - testapp
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.3.8', '2.4.5', '2.5.2']
        rails: ['42', '50', '51', '52']
        include:
          - rails: '42'
            gemfile: gemfiles/rails_42.gemfile
          - rails: '50'
            gemfile: gemfiles/rails_50.gemfile
          - rails: '51'
            gemfile: gemfiles/rails_51.gemfile
          - rails: '52'
            gemfile: Gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      COVERAGE: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install bundler
        run: gem install bundler -v 1.17.1

      - name: Install dependencies
        run: bundle install --path vendor/bundle --retry 3 --jobs 3

      - name: Install chromedriver
        run: bin/install_chromedriver.sh

      - name: Download test app
        uses: actions/download-artifact@v4
        with:
          name: testapp-rails${{ matrix.rails }}
          path: spec/rails

      - name: Restore test times cache
        uses: actions/cache@v4
        with:
          path: |
            tmp/parallel_runtime_rspec.log
            tmp/parallel_runtime_cucumber.log
          key: testtime-${{ github.ref_name }}-ruby${{ matrix.ruby }}rails${{ matrix.rails }}
          restore-keys: |
            testtime-master-ruby${{ matrix.ruby }}rails${{ matrix.rails }}

      - name: Download test-reporter
        uses: actions/download-artifact@v4
        with:
          name: test-reporter
          path: tmp

      - name: Make test-reporter executable
        run: chmod +x tmp/test-reporter

      - name: Run tests
        run: |
            mkdir -p spec/rails/rails-5.0.7.1/app/assets/javascripts/channels
            mkdir -p spec/rails/rails-5.1.6.1/app/assets/javascripts/channels
            mkdir -p spec/rails/rails-5.2.1.1/app/assets/javascripts/channels
            COVERAGE=true PARALLEL_TEST_PROCESSORS=4 bundle exec rake test

      - name: Format coverage
        run: tmp/test-reporter format-coverage --input-type simplecov --output tmp/codeclimate.ruby${{ matrix.ruby }}rails${{ matrix.rails }}.json
        continue-on-error: true

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-ruby${{ matrix.ruby }}rails${{ matrix.rails }}
          path: tmp/codeclimate.ruby${{ matrix.ruby }}rails${{ matrix.rails }}.json
          if-no-files-found: ignore

  # Test jobs for JRuby versions
  test_jruby:
    runs-on: ubuntu-22.04
    needs: 
        - setup_coverage
        - testapp
    strategy:
      fail-fast: false
      matrix:
        jruby: ['9.1', '9.2']
        rails: ['42', '50', '51', '52']
        include:
          - rails: '42'
            gemfile: gemfiles/rails_42.gemfile
          - rails: '50'
            gemfile: gemfiles/rails_50.gemfile
          - rails: '51'
            gemfile: gemfiles/rails_51.gemfile
          - rails: '52'
            gemfile: Gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      COVERAGE: true
      JRUBY_OPTS: -J-Xmx1024m --dev --debug
    steps:
      - uses: actions/checkout@v4

      - name: Set up JRuby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: jruby-${{ matrix.jruby }}

      - name: Install bundler
        run: gem install bundler -v 1.17.1

      - name: Install dependencies
        run: bundle install --path vendor/bundle --retry 3 --jobs 3

      - name: Install chromedriver
        run: bin/install_chromedriver.sh

      - name: Download test app
        uses: actions/download-artifact@v4
        with:
          name: testapp-rails${{ matrix.rails }}
          path: spec/rails

      - name: Restore test times cache
        uses: actions/cache@v4
        with:
          path: |
            tmp/parallel_runtime_rspec.log
            tmp/parallel_runtime_cucumber.log
          key: testtime-${{ github.ref_name }}-jruby${{ matrix.jruby }}rails${{ matrix.rails }}
          restore-keys: |
            testtime-master-jruby${{ matrix.jruby }}rails${{ matrix.rails }}

      - name: Download test-reporter
        uses: actions/download-artifact@v4
        with:
          name: test-reporter
          path: tmp

      - name: Make test-reporter executable
        run: chmod +x tmp/test-reporter

      - name: Run tests
        run: |
            mkdir -p spec/rails/rails-5.0.7.1/app/assets/javascripts/channels
            mkdir -p spec/rails/rails-5.1.6.1/app/assets/javascripts/channels
            mkdir -p spec/rails/rails-5.2.1.1/app/assets/javascripts/channels
            COVERAGE=true PARALLEL_TEST_PROCESSORS=4 bundle exec rake test

      - name: Format coverage
        run: tmp/test-reporter format-coverage --input-type simplecov --output tmp/codeclimate.jruby${{ matrix.jruby }}rails${{ matrix.rails }}.json
        continue-on-error: true

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-jruby${{ matrix.jruby }}rails${{ matrix.rails }}
          path: tmp/codeclimate.jruby${{ matrix.jruby }}rails${{ matrix.rails }}.json
          if-no-files-found: ignore
